name: IOS Production Build

on:
  workflow_dispatch:
  release:
    types: [published] # only run the workflow when a new release has been published

jobs:
  ios-build:
    name: IOS Production Build
    runs-on: macOS-latest
    defaults:
      run:
        working-directory: ios

    steps:
     -  name : Checkout Repo 
        uses : actions/checkout@v3
     
     -  name : Npm Install
        uses : actions/setup-node@v3
        with :
          node-version: 14
          cache: 'npm'
     -  run : npm install
     -  run : npm build:ios

     -  name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with :
           ruby-version: 2.6
           bundler-cache: true

     -  name: Install Pods
        working-directory: ios
        run: arch -x86_64 pod install

     - name: Build IOS App
       uses: yukiarrr/ios-build-action@v1.4.0
       with:
          project-path: ios/Khawla.xcodeproj
          p12-base64: ${{ secrets.IOS_P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.IOS_MOBILE_PROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.IOS_TEAM_ID }}
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          workspace-path: ios/Khawla.xcworkspace
          scheme: Khawla

     - name: 'Upload app to TestFlight'
       uses: apple-actions/upload-testflight-build@v1
       with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
